---
- name: Deploy and Onboard Microsoft Defender on Linux
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Install prerequisite packages
      ansible.builtin.raw: |
        DEBIAN_FRONTEND=noninteractive apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get --fix-broken install -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y curl apt-transport-https gnupg python3
      changed_when: false
    - name: Add Microsoft GPG key
      ansible.builtin.raw: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/microsoft.gpg
        changed_when: false

    - name: Add Microsoft Defender repository
      ansible.builtin.raw: |
        curl -sSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list -o /etc/apt/sources.list.d/microsoft-prod.list
      changed_when: false  

    - name: Install Microsoft Defender (mdatp)
      ansible.builtin.raw: |
        DEBIAN_FRONTEND=noninteractive apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y mdatp
      changed_when: false

    - name: Copy Onboarding Script to Target Machine
      ansible.builtin.raw: |
        cat << 'EOF' > /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py
        {{ lookup('file', 'MicrosoftDefenderATPOnboardingLinuxServer.py') }}
        EOF
        chmod +x /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py
      changed_when: false

    - name: Run Onboarding Script
      ansible.builtin.raw: python3 /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py
      changed_when: false
      
    - name: Check mdatp status
      ansible.builtin.raw: mdatp health
      changed_when: false

