---
- name: Deploy and Onboard Microsoft Defender on Linux
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Install prerequisite packages
      ansible.builtin.raw: apt-get update && apt-get install -y curl apt-transport-https gnupg python3
      changed_when: false
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft Defender repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main"
        state: present
        filename: microsoft-prod

    - name: Install Microsoft Defender (mdatp)
      apt:
        name: mdatp
        state: latest
        update_cache: yes

    - name: Copy Onboarding Script to Target Machine
      copy:
        src: MicrosoftDefenderATPOnboardingLinuxServer.py
        dest: /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py
        mode: '0755'

    - name: Run Onboarding Script
      command: python3 /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py

    - name: Check mdatp status
      command: mdatp health
      register: mdatp_health

    - name: Display Defender Status
      debug:
        var: mdatp_health.stdout_lines
